#!/bin/bash

# Copyright: Ren Tatsumoto
# License: GNU GPL, version 3 or later; http://www.gnu.org/licenses/gpl.html

set -euo pipefail

readonly NC='\033[0m'
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'

readonly config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/neocities
declare site_directory api_key

request() {
	curl -s -H "Authorization: Bearer ${api_key:?}" "$@"
}

list() {
	request "https://neocities.org/api/list"
}

info() {
	request "https://neocities.org/api/info"
}

sitename() {
	info | grep -Po '(?<="sitename":\s").*(?=")'
}

list_remote_files_and_sums() {
	# For each remote file, print its relative path and sha1 sum
	list | python3 -c '
import sys, json
content = json.loads(sys.stdin.read())
for file_info in content["files"]:
    if file_info["is_directory"] is False:
        print(file_info["path"], file_info["sha1_hash"], sep="\t")
'
}

download_backup() {
	# Download the entire site to the current directory.
	local -r site_name=$(sitename)
	local -r backup_folder="${site_name:?}-$(date -u)"
	local full_url rel_path
	mkdir -p "$backup_folder" && cd -- "$backup_folder" || exit 1

	while IFS= read -r rel_path; do
		full_url="https://$site_name.neocities.org/$rel_path"
		mkdir -p -- "$(dirname -- "$rel_path")"
		if curl -s "$full_url" -o "$rel_path"; then
			echo -e "${GREEN}[OK]${NC} $rel_path"
		else
			echo -e "${RED}[FAIL]${NC} $rel_path"
		fi
	done <<<"$(list_remote_files_and_sums | cut -f1)"
}

list_local_files() {
	if [[ ${no_git-} == true ]]; then
		find . -type f -printf '%p\n' |
			sed -e 's|^\./||'
	else
		cd -- "$(git rev-parse --show-toplevel)" || exit 1
		git ls-files
	fi | grep -Pv '/?\.git(ignore)?($|/)' || true
}

list_pending_file_changes() {
	local -A local_sums remote_sums
	local rel_path remote_sum

	# Remember local checksums
	while IFS= read -r rel_path; do
		local_sums[$rel_path]=$(sha1sum -- "$rel_path" | cut -f1 -d' ')
	done <<<"$(list_local_files)"

	# Remember remote checksums
	while IFS=$'\t' read -r rel_path remote_sum; do
		remote_sums[$rel_path]=$remote_sum
	done <<<"$(list_remote_files_and_sums)"

	# List files to be updated
	for rel_path in "${!local_sums[@]}"; do
		if [[ "${local_sums[$rel_path]}" != "${remote_sums[$rel_path]-}" ]]; then
			echo -e "upload\t$rel_path"
		fi
	done | sort -u

	# List files to be deleted
	for rel_path in "${!remote_sums[@]}"; do
		if [[ -z "${local_sums[$rel_path]-}" ]]; then
			echo -e "delete\t$rel_path"
		fi
	done | sort -u
}

upload() {
	local -r file=$1
	if [[ -f $file ]]; then
		request -F "$file=@$file" "https://neocities.org/api/upload" | parse_request_result
	else
		echo "'$file' is not a file or doesn't exist."
	fi
}

delete() {
	local -r file=$1
	request -d "filenames[]=$file" "https://neocities.org/api/delete" | parse_request_result
}

parse_request_result() {
	local -r msg=$(cat -)
	if echo "$msg" | grep -q -P '"result":\s*"success"'; then
		echo -e "${GREEN}[OK]${NC} ${file:?}"
	else
		echo -e "${RED}[FAIL]${NC} ${file:?}"
		if [[ ${verbose-} == true ]]; then
			echo "$msg"
		fi
	fi
}

update_site() {
	local action rel_path
	while IFS=$'\t' read -r action rel_path; do
		"$action" "$rel_path"
	done <<<"$(list_pending_file_changes)"
}

read_config() {
	# shellcheck source=/dev/null
	if [[ -f ${config_filepath:?} ]]; then
		source "$config_filepath"
	else
		echo "Can't find config file."
		exit 1
	fi
	unset config_filepath
	readonly site_directory api_key
	cd -- "${site_directory:?}" || exit 1
}

help() {
	echo "Usage: $(basename -- "$(readlink -f -- "$0")") [OPTION] [FILE]"
	echo
	echo "A Neocities client written in Bash."
	echo
	column -t -s'|' <<-EOF
		Options:
		-h, --help|display this help text and exit
		-V, --verbose|verbose mode
		-p, --profile|specify the desired profile name
		-n, --no-git|don't use git to list files
		init NAME|create a new profile with NAME
		push|upload all files that differ from the remote
		status|lists all files that differ from the remote
		list|print all remote files
		download|download a backup of the site
		upload FILE|upload a file
		delete FILE|delete a file from the remote
	EOF
}

init() {
	local -r new_config=$config_dir/$user
	mkdir -p -- "$config_dir"
	if [[ -f $new_config ]]; then
		echo "This profile already exists."
	else
		cat <<-EOF >"$new_config"
			site_directory=~/Documents/my_site
			api_key=da77c3530c30593663bf7b797323e48c
		EOF
		echo "Created a new config file $new_config"
	fi
}

with_stash() {
	if [[ ${no_git-} == true ]]; then
		"$@"
	else
		git stash >/dev/null
		"$@"
		git stash pop >/dev/null
	fi
}

main() {
	if (($# == 0)); then
		help
		exit
	fi
	while :; do
		case ${1-} in
		-h | --help)
			help
			exit
			;;
		-V | --verbose)
			readonly verbose=true
			;;
		-n | --no-git)
			readonly no_git=true
			;;
		-p | --profile)
			shift
			local config_filepath=$config_dir/${1:?Profile name is not set.}
			read_config
			;;
		init)
			local -r user=${2:?Please provide a profile name.}
			init
			exit
			;;
		push)
			with_stash update_site
			exit
			;;
		status)
			echo "Pending changes on the remote:"
			with_stash list_pending_file_changes
			exit
			;;
		list)
			list_remote_files_and_sums | cut -f1
			exit
			;;
		download)
			download_backup
			exit
			;;
		upload)
			upload "$2"
			exit
			;;
		delete)
			delete "$2"
			exit
			;;
		"")
			break
			;;
		*)
			echo "Unknown command: '$1'"
			exit 1
			;;
		esac
		shift
	done
}

main "$@"
